version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: queueserver
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'
      - '15672:15672'