version: '3.6'
services:

  api-layer:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: expressserver
    volumes:
      - ./:/usr/src/app # Mount the local project directory to the container
    restart: "always"
    networks: 
      - api-layer
    command: bash -c "node index.js" 
    ports:
      - "5000:5000" 

  withdrawlservice:
    build:
      context: ./withdrawlservice
      dockerfile: Dockerfile
    container_name: expressserver
    volumes:
      - ./:/usr/src/app # Mount the local project directory to the container
    restart: "always"
    networks: 
      - api-layer
    command: bash -c "node index.js" 
    ports:
      - "8000:8000"     
      
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - expressserver
    networks:
      - api-layer

networks:
      api-layer: {}      
